# Generated by Django 3.2.6 on 2021-08-08 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaddata', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('notesfile', models.FileField(upload_to='')),
                ('filetype', models.CharField(max_length=20)),
                ('desciription', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
