# Generated by Django 3.2.6 on 2021-08-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
