# Generated by Django 3.2.6 on 2021-08-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_delete_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='author',
        ),
    ]
