# Generated by Django 3.2.6 on 2021-08-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='desciription',
            new_name='description',
        ),
    ]
